set -x

export VLLM_ATTENTION_BACKEND=XFORMERS
export TOKENIZERS_PARALLELISM='true'

train_files="math_train_verl.parquet"
test_files="math_test_verl.parquet"
offload=False
adv_estimator=ktae
train_batch_size=1024
lr=1e-6
ppo_mini_batch_size=128
inf_temperature=1.0
rollout_n=16
use_kl_loss=True
kl_loss_coef=0.001
alpha=1.0
beta_ig=2.0
gamma_tf=1.0
max_response_length=3072
model_path="Qwen2.5-Math-1.5B"
save_freq=10
test_freq=5
val_before_train=True
total_epochs=20
top=1.0
bottom=-1.0
seed=0
use_dynamic_bsz=True
project_name='DAPO-verl-Qwen2.5-1.5B-Math'
# project_name='test'
experiment_name=""


python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator="$adv_estimator" \
    algorithm.alpha=$alpha \
    algorithm.beta_ig=$beta_ig \
    algorithm.gamma_tf=$gamma_tf \
    algorithm.top=$top \
    algorithm.bottom=$bottom \
    algorithm.use_kl_in_reward=False \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=$train_batch_size \
    data.max_prompt_length=1024 \
    data.max_response_length=$max_response_length \
    data.filter_overlong_prompts=False \
    data.truncation='left' \
    actor_rollout_ref.model.path=$model_path  \
    actor_rollout_ref.actor.optim.lr=$lr \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_mini_batch_size=$ppo_mini_batch_size \
    actor_rollout_ref.actor.use_kl_loss=$use_kl_loss \
    actor_rollout_ref.actor.kl_loss_coef=$kl_loss_coef \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=${offload} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.engine_seed=$seed \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=$rollout_n \
    actor_rollout_ref.rollout.val_kwargs.do_sample=False \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.rollout.temperature=$inf_temperature \
    trainer.logger=['console','wandb'] \
    trainer.project_name="$project_name" \
    trainer.experiment_name="$experiment_name" \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=$save_freq \
    trainer.test_freq=$test_freq \
    trainer.val_before_train=$val_before_train \
    trainer.total_epochs=$total_epochs $@